version: 1.2
workflows:
  - name: annotate_variants
    publish: True
    primaryDescriptorPath: /pipeline/annotate_variants.wdl
    subclass: WDL
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - main

  - name: hgvs
    publish: True
    primaryDescriptorPath: /pipeline/hgvs/hgvs.wdl
    subclass: WDL
    testParameterFiles:
      - /pipeline/hgvs/test.json
    filters: # All tags, no branches
      branches:
        - main

  - name: mask_variants
    publish: True
    primaryDescriptorPath: /pipeline/mask_variants.wdl
    subclass: WDL
    filters: # All tags, no branches
      branches:
        - main

  - name: opencravat_dm
    publish: True
    primaryDescriptorPath: /pipeline/opencravat_dm.wdl
    subclass: WDL
    filters: # All tags, no branches
      branches:
        - main

  - name: remove_filtered
    publish: True
    primaryDescriptorPath: /pipeline/remove_filtered.wdl
    subclass: WDL
    filters: # All tags, no branches
      branches:
        - main
  
  - name: vcf2maf
    publish: True
    primaryDescriptorPath: /pipeline/vcf2maf/vcf2maf.wdl
    subclass: WDL
    testParameterFiles:
      - /pipeline/vcf2maf/test.json
    filters: # All tags, no branches
      branches:
        - main

  - name: vcf_to_depmap
    publish: True
    primaryDescriptorPath: /pipeline/vcf_to_depmap/vcf2maf.wdl
    subclass: WDL
    filters: # All tags, no branches
      branches:
        - main

