version: 1.2

name: annotate_variants
  publish: True
  primaryDescriptorPath: .\annotate_variants.wdl
  subclass: WDL
  testParameterFiles:
    - /test.json
  filters: # All tags, no branches
    branches:
      - master
name: hgvs
  publish: True
  primaryDescriptorPath: .\hgvs.wdl
  subclass: WDL
  testParameterFiles:
    - /test.json
  filters: # All tags, no branches
    branches:
      - master

name: mask_variants
  publish: True
  primaryDescriptorPath: .\mask_variants.wdl
  subclass: WDL
  testParameterFiles:
    - /test.json
  filters: # All tags, no branches
    branches:
      - master

name: opencravat_dm
  publish: True
  primaryDescriptorPath: .\opencravat_dm.wdl
  subclass: WDL
  testParameterFiles:
    - /test.json
  filters: # All tags, no branches
    branches:
      - master

name: remove_filtered
  publish: True
 primaryDescriptorPath: .\remove_filtered.wdl
  subclass: WDL
  testParameterFiles:
    - /test.json
  filters: # All tags, no branches
    branches:
      - master

