version: 1.2

name: .\annotate_variants.wdl
  subclass: WDL
  
name: .\hgvs.wdl
  subclass: WDL
name: .\mask_variants.wdl
  subclass: WDL

name: .\opencravat_dm.wdl
  subclass: WDL

name: .\remove_filtered.wdl
  subclass: WDL

