language: perl
os: linux
dist: bionic
services: docker

branches:
  only:
    - main

install:
  - docker build -t vcf2maf:main .
  - docker image prune -f
  - wget -P tests https://data.cyri.ac/Homo_sapiens.GRCh38.dna.chromosome.21.fa.gz
  - gzip -d tests/Homo_sapiens.GRCh38.dna.chromosome.21.fa.gz
  - wget -P tests https://data.cyri.ac/homo_sapiens_vep_102_GRCh38_chr21.tar.gz
  - tar -zxf tests/homo_sapiens_vep_102_GRCh38_chr21.tar.gz -C tests

script:
  - perl tests/vcf2maf.t
  - perl tests/vcf2vcf.t
  - perl tests/maf2vcf.t
